# Default values for node-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

service:
  name: "my-service"

hpaEnabled: true
metric: "cpu"
metricUtilization: 50
maxReplicas: 10
minReplicas: 1