{{- if eq .Values.enabled true }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      service: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        service: {{ .Values.service.name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
      - name: {{ .Values.service.name }}-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        ports:
        - containerPort: {{ .Values.service.port }}
        {{- include "node-service.livenessProbe" . | nindent 8 }}
        {{- include "node-service.readinessProbe" . | nindent 8 }}
        envFrom:
        - configMapRef:
            name: {{ .Values.service.name }}-env-vars
            optional: false
{{- end }}
