{{- if eq .Values.enabled true }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
{{- if .Values.ingress.annotations }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
{{- end }}
  labels:
    service: {{ .Values.service.name }}
  name: {{ .Values.service.name }}-ingress
spec:
  rules:
    {{- toYaml .Values.ingress.rules | nindent 4 }}
{{- end }}
